<?xml version="1.0" ?>
<robot name="body" xmlns:xacro="http://ros.org/wiki/xacro">
<link name="base_link" />

<xacro:property name="b_m" value="5.58"/>
<xacro:property name="b_m2" value="${b_m/12}"/><!--for calculation of inertia-->
<xacro:property name="b_w" value="0.44"/>
<xacro:property name="b_h" value="0.44"/>
<xacro:property name="b_d" value="0.44"/>

<link name="body">
   <visual>
　　<geometry>
　　　<box size="${b_d} ${b_w} ${b_h}" />
     </geometry>
  </visual>
   <collision>
　　<geometry>
　　　<box size="${b_d*0.95} ${b_w*0.95} ${b_h*0.95}" />
     </geometry>
  </collision>
  <inertial>
     <origin xyz="0 0 0" rpy="0 0 0" />
     <mass value="${b_m}" />
    <inertia ixx="${b_m2*(b_h*b_h+b_w*b_w)}" ixy="0"    ixz="0"
                 iyx="0"   iyy="${b_m2*(b_h*b_h+b_d*b_d)}"  iyz="0"
		 izx="0"   izy="0"  izz="${b_m2*(b_w*b_w+b_d*b_d)}" />
  </inertial>
</link>

<joint name="body_joint" type="fixed">
<parent link="base_link" />
   <child link="body" />
   <origin xyz="0 0 0.230" rpy="0 0 0" />
</joint>

<!--support wheel-->
  <joint name="ball_joint_1" type="fixed">
    <parent link="base_link"/>
    <child  link="ball_link_1"/>
    <origin xyz="0.21 0 0.01" rpy="0 0 0"/>
  </joint>
  <link name="ball_link_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
      <material name="gray" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
      <material name="gray" />
    </collision>
  </link>
  <gazebo reference="ball_link_1">
    <material>Gazebo/Gray</material>
    <mu1 value="0.5" />
    <mu2 value="0.5" />
  </gazebo>

  <joint name="ball_joint_2" type="fixed">
    <parent link="base_link"/>
    <child  link="ball_link_2"/>
    <origin xyz="-0.21 0 0.01" rpy="0 0 0"/>
  </joint>
  <link name="ball_link_2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
      <material name="gray" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.01" />
      </geometry>
      <material name="gray" />
    </collision>
  </link>
  <gazebo reference="ball_link_2">
    <material>Gazebo/Gray</material>
    <mu1 value="0.5" />
    <mu2 value="0.5" />
  </gazebo>

</robot>

