image: angkorcenter_map.png
resolution: 0.025
origin: [-6.0, 6.0, 0.0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

# image : Path to the image file containing the occupancy data; can be absolute, or relative to the location of the YAML file

# resolution : Resolution of the map, meters / pixel

# origin : The 2-D pose of the lower-left pixel in the map, as (x, y, yaw), with yaw as counterclockwise rotation (yaw=0 means no rotation). Many parts of the system currently ignore yaw.

# occupied_thresh : Pixels with occupancy probability greater than this threshold are considered completely occupied.

# free_thresh : Pixels with occupancy probability less than this threshold are considered completely free.

# negate : Whether the white/black free/occupied semantics should be reversed (interpretation of thresholds is unaffected)