<?xml version="1.0" ?>
<robot name="wheel"
  xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_height" value="0.05"/>
  <xacro:property name="wheel_mass" value="0.50"/>

  <xacro:macro name="wheel" params="rl parent">

    <xacro:property name="b_m" value="0.1"/>
    <xacro:property name="b_m2" value="${b_m/12}"/>
    <!--for calculation of inertia-->
    <xacro:property name="b_w" value="0.01"/>
    <xacro:property name="b_h" value="0.05"/>
    <xacro:property name="b_d" value="0.05"/>

    <link name="wheel_${rl}_round_table">
      <visual>
        <geometry>
          <box size="${b_d} ${b_w} ${b_h}" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${b_d*0.95} ${b_w*0.95} ${b_h*0.95}" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${b_m}" />
        <inertia ixx="${b_m2*(b_h*b_h+b_w*b_w)}" ixy="0" ixz="0" iyx="0" iyy="${b_m2*(b_h*b_h+b_d*b_d)}" iyz="0" izx="0" izy="0" izz="${b_m2*(b_w*b_w+b_d*b_d)}" />
      </inertial>
    </link>

    <link name="wheel_${rl}">
      <visual>
        <geometry>
          <cylinder length="${wheel_height}" radius="${wheel_radius}" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_height}" />
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>1</mu>
              <mu2>1</mu2>
              <slip1>0.035</slip1>
              <slip2>0</slip2>
              <fdir1>0 0 1</fdir1>
            </ode>
          </friction>
        </surface>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_height*wheel_height)/12}" ixy="0" ixz="0" iyx="0" iyy="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_height*wheel_height)/12}" iyz="0" izx="0" izy="0" izz="${wheel_mass*(wheel_radius*wheel_radius)/2}" />
      </inertial>
    </link>

    <joint name="wheel_${rl}_joint" type="continuous">
      <parent link="wheel_${rl}_round_table" />
      <child link="wheel_${rl}" />
      <origin xyz="0.0 -0.05 0.0" rpy="0 ${PI/2} 0" />
      <!--z: position from base_link - position from body-->
      <axis xyz="0 0 -1" />
      <limit effort="6.0" velocity="60.0" />
      <!-- maximum torqe(<8.82), maximum velocity-->
      <dynamics damping="0.1"/>
    </joint>

    <joint name="wheel_${rl}_angular_joint" type="continuous">
      <parent link="${parent}" />
      <child link="wheel_${rl}_round_table" />
      <xacro:if value="${rl == 'rf'}">
        <origin xyz="0.22 -0.22 0.085" rpy="${PI/2} 0 0" />
        <!--z: position from base_link - position from body-->
      </xacro:if>
      <xacro:if value="${rl == 'lf'}">
        <origin xyz="0.22 0.22 0.085" rpy="${PI/2} 0 0" />
      </xacro:if>
      <xacro:if value="${rl == 'rb'}">
        <origin xyz="-0.22 -0.22 0.085" rpy="${PI/2} 0 0" />
        <!--z: position from base_link - position from body-->
      </xacro:if>
      <xacro:if value="${rl == 'lb'}">
        <origin xyz="-0.22 0.22 0.085" rpy="${PI/2} 0 0" />
      </xacro:if>
      <axis xyz="0 1 0" />
      <limit effort="6.0" velocity="12.0" />
      <!-- maximum torqe(<8.82), maximum velocity-->
      <dynamics damping="0.1"/>
    </joint>

    <!-- <gazebo>
            <plugin filename="ignition-gazebo-joint-controller-system" name="ignition::gazebo::systems::JointController">
                <joint_name>wheel_${rl}_joint</joint_name>
                <joint_name>wheel_${rl}_angular_joint</joint_name>
            </plugin>
        </gazebo> -->

  </xacro:macro>
</robot>
