<?xml version="1.0"?>
<robot name="odm_robot"
    xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find nhk2023_simulator)/urdf/lidar.urdf.xacro" />
    <xacro:include filename="$(find nhk2023_simulator)/urdf/imu.urdf.xacro" />

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="b_m" value="20.0"/>
    <xacro:property name="b_m2" value="${b_m/12}"/>
    <!--for calculation of inertia-->
    <xacro:property name="b_w" value="0.60"/>
    <xacro:property name="b_h" value="0.1"/>
    <xacro:property name="b_d" value="0.60"/>
    <xacro:property name="lidar_w" value="0.64"/>

    <material name="red">
        <color rgba="0.2 0 0 1"/>
    </material>

    <link name="base_link"/>

    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        <origin xyz="0 0 ${b_h/2}" rpy="0 0 0"/>
    </joint>
    <link name="body_link">
        <visual>
            <geometry>
                <box size="${b_d} ${b_w} ${b_h}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${b_d*0.95} ${b_w*0.95} ${b_h*0.95}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${b_m}" />
            <inertia ixx="${b_m2*(b_h*b_h+b_w*b_w)}" ixy="0" ixz="0" iyx="0" iyy="${b_m2*(b_h*b_h+b_d*b_d)}" iyz="0" izx="0" izy="0" izz="${b_m2*(b_w*b_w+b_d*b_d)}" />
        </inertial>
    </link>
    <gazebo reference="body_link">
        <material>Gazebo/Red</material>
        <mu1 value="0.1" />
        <mu2 value="0.1" />
    </gazebo>

    <!-- <joint name="head_joint" type="fixed">
    <parent link="base_link"/>
    <child link="head_link"/>
    <origin xyz="0.05 0 0.12" rpy="0 0 0"/>
  </joint>
  <link name="head_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.04"/>
      </geometry>
      <material name="red" />
    </visual>
  </link>
  <gazebo reference="head_link">
    <material>Gazebo/Red</material>
  </gazebo> -->

    <xacro:laser_macro prefix="lidar1" parent="base_link" xyz="${lidar_w/2} -${lidar_w/2} 0.04" rpy="0 0 -${PI/4}" />
    <xacro:laser_macro prefix="lidar2" parent="base_link" xyz="-${lidar_w/2} ${lidar_w/2} 0.04" rpy="0 0 ${3*PI/4}" />

    <xacro:imu_macro prefix="imu" parent="base_link" xyz="0.0 0 0.10" />


    <gazebo>
        <plugin name="ignition::gazebo::systems::VelocityControl" filename="ignition-gazebo-velocity-control-system">
        </plugin>
    </gazebo>
</robot>